name: 'Tests and coverage - PR'

on:
  pull_request:
    types: [synchronize, opened]

jobs:
  codecoverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: Borales/actions-yarn@v2.1.0
      - name: 'Setup'
        run: yarn install
      - name: 'Run tests'
        run: yarn test --coverage
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} #required
          file: ./coverage/coverage-final.json
          fail_ci_if_error: true #optional (default = false)
